---
- hosts: master
  user: root
  become: yes
  gather_facts: no
  vars:

  tasks:

    - name: export config of the cluster
      shell: kubectl get configmaps -n kube-system kubeadm-config -o yaml > /tmp/clusterconfig1.yaml

    - name: replace name of the cluster
      lineinfile:
        path: /tmp/clusterconfig.yaml
        regexp: '(.*)clusterName(.*)$'
        line: '\\s clusterName: case-ozkanpoyrazoglu.abc'
        backrefs: yes

    - name: import config
      shell: kubectl apply -f /tmp/clusterconfig1.yaml
      ignore_errors: yes


